services:
  backend:
    build: ./remix-backend
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=remixdb;Username=postgres;Password=postgres
    depends_on:
      - db

  frontend:
    build: ./remix-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: remixdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
