name: Deploy Backend to Azure

on:
  push:
    paths:
      - 'remix-backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: remix-backend-luz
          publish-profile: ${{secrets.AZURE_BACKEND_PUBLISH}}
          package: ./remix-backend
