name: Deploy Backend to Azure

on:
  push:
    paths:
      - 'remix-backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # O la versión que uses

      - name: Restore .NET backend dependencies
        working-directory: remix-backend
        run: dotnet restore

      - name: Build .NET backend
        working-directory: remix-backend
        run: dotnet build --configuration Release --no-restore

      - name: Publish .NET backend
        working-directory: remix-backend
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WeatherForecastAppLuzBackend
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH }}
          package: remix-backend/publish

